name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install httpie

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Deploy
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: -avzr --delete
          options: ''
          ssh_options: ''
          src: './'
          dest: ${{ secrets.DEPLOY_USER }}@noproxy.iwgb.org.uk:/var/repo/iwgb-link

      - name: Build
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: noproxy.iwgb.org.uk
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/repo/iwgb-link/.deploy
            sh ./deploy.sh

      - name: Verify
        run: echo ::set-env name=status::$(http -h https://iwgb.link/api/health | grep HTTP/ | cut -d ' ' -f 2)

      - name: Check
        if: env.status == 500
        run: http POST https://maker.ifttt.com/trigger/build_failed/with/key/${{ secrets.IFTTT_KEY }} value1="${{ github.workflow }}" value2="${{ github.repository }}" --ignore-stdin && exit 1

      - name: Validate
        if: env.status != 500
        run: http POST https://maker.ifttt.com/trigger/build_success/with/key/${{ secrets.IFTTT_KEY }} value1="${{ github.workflow }}" value2="${{ github.repository }}" --ignore-stdin
